language: java
jdk:
  - oraclejdk7

sudo: true
addons:
  apt:
    sources:
    - sourceline: 'ppa:brightbox/ruby-ng'
    packages:
    - ruby2.3
    - ruby2.3-dev

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script: pushd tools/test_server && ruby2.3 -S bundle install && ruby2.3 -S bundle exec rake start && popd
after_script: pushd tools/test_server && ruby2.3 -S bundle exec rake stop && popd
